### ISSUE TITLE
Error when use `rum/local` and `rum/use-callback` together

### ISSUE THREAD

**Issue by wangchunsen** [tonsky/rum#248]
When I am trying to define a component using `rum/local` and `rum/use-callback` together like:
```clojure
(defc about-page < (rum/local {} ::users) []
  (let [c-fn (rum/use-callback (fn [] (println "")))]
  [:span.main
   [:h1 "About some page"]]))
```   
Then I get an error, says:
```
react_devtools_backend.js:4061 error when calling lifecycle function movie-fr.core/on-reload Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js:14907:13)
    at Object.exports.useCallback (react.development.js:1529:21)
    at Function.eval [as cljs$core$IFn$_invoke$arity$1] (core.cljs:615:18)
    at Function.eval (core.cljs:48:15)
    at Function.eval [as cljs$core$IFn$_invoke$arity$3] (core.cljs:3935:15)
    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (core.cljs:3930:7)
    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (core.cljs:3965:7)
    at render (core.cljs:208:32)
    at eval (core.cljs:112:50)
    at ctor.eval [as render] (core.cljs:112:49)
overrideMethod @ react_devtools_backend.js:4061
eval @ env.cljs:214
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:220
G__62703 @ env.cljs:220
eval @ env.cljs:215
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:220
G__62703 @ env.cljs:220
eval @ env.cljs:249
shadow$cljs$devtools$client$env$do_js_reload_STAR_ @ env.cljs:220
eval @ env.cljs:256
shadow$cljs$devtools$client$browser$do_js_reload @ browser.cljs:43
eval @ browser.cljs:93
eval @ shared.cljs:32
shadow$remote$runtime$shared$process @ shared.cljc:164
eval @ shared.cljs:289
shadow$cljs$devtools$client$shared$remote_msg @ shared.cljs:16
eval @ websocket.cljs:16
```

But when I remove `rum/local`,  it works agin
```clojure
(defc about-page []
  (let [c-fn (rum/use-callback (fn [] (println "")))]
  [:span.main
   [:h1 "About some page"]]))
```   

I am using rum of version **0.12.8**, anyone has an idea?

**Comment by martinklepsch** [comment]
You can only use hooks in components that either a) don't have mixins or b) use only the `rum/static` mixin. I think this is because other mixins will turn the component into a class-based component, which are not allowed to use hooks (see [React FAQ](https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both))

Instead of `local` you'd probably want to use `rum/use-state`.

**Comment by wangchunsen** [comment]
Thank you, it makes sense.  
I think it would be nice if there are some document that describes the limitation of the use case.
